version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 3000:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=pasword
      - POSTGRESQL_DATABASE=apisolid