version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 3000:5432
    environment:
      - POSTGRESQL_USERNAME=mypets
      - POSTGRESQL_PASSWORD=mypets
      - POSTGRESQL_DATABASE=solidpets